# yaml-language-server: $schema=https://dashboard.mergify.com/config-schemas/mergify-schema-v2.json
pull_request_rules:
  - name: Label on PKGBUILD Changes
    conditions:
      - files ~= PKGBUILD$
    actions:
      label:
        toggle:
          - AUR
  - name: Label on pre-commit Updates
    conditions:
      - files ~= .pre-commit-config.yaml
    actions:
      label:
        toggle:
          - pre-commit
  - name: Label on Dockerfile Updates
    conditions:
      - files ~= Dockerfile$
    actions:
      label:
        toggle:
          - docker
  - name: Label on Github Actions Updates
    conditions:
      - files ~= ^.github/workflows
    actions:
      label:
        toggle:
          - github-actions
          - CI
  - name: Label on Python Dependency Updates
    conditions:
      - files ~= ^(uv.lock|pyproject.toml)$
    actions:
      label:
        toggle:
          - uv
          - python
          - dependencies
  - name: Label on Docker Compose Updates
    conditions:
      - files ~= ^(docker-compose-dev.yaml|docker-compose.yaml)$
    actions:
      label:
        toggle:
          - docker-compose
  - name: Merge pull request when the configuration of Mergify is valid
    conditions:
      - author = MH0386
      - "title = ci(Mergify): configuration update"
      - head = mergify/MH0386/config-update
    actions:
      merge:
  - name: Comment when a pull request is merged
    conditions:
      - merged
    actions:
      comment:
        message: >-
          Thank you for your contribution @{{author}}! Your pull request has been merged.
  - name: Comment if there is a conflict
    conditions:
      - conflict
    actions:
      comment:
        message: Hi @{{author}}, Your PR is in conflict and cannot be merged.
      label:
        toggle:
          - conflict
  - name: Automatic update of the pull requests
    conditions:
      - -merged
    actions:
      update:
  - name: Ping PR author when conflicting with labellng
    description: Warn the pull request author when their PR are conflicting and add a label
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
      comment:
        message: >-
          👋 {{author}} your PR is conflicting and needs to be updated to be merged
  - name: Label Mergify Stacks PRs
    description: Pull requests that are part of a Mergify stack should be labeled as such
    conditions:
      - "commits[0].commit_message ~= (?m)Change-Id:"
    actions:
      label:
        toggle:
          - stack
  - name: Label first PR of Mergify Stacks PRs
    description: The first PR of a Mergify stack should be labeled as such
    conditions:
      - "commits[0].commit_message ~= (?m)Change-Id:"
      - -base ~= ^mergify_cli/
    actions:
      label:
        toggle:
          - top of the stack
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued
  - name: Notify when a PR is removed from the queue
    description: Notify the PR author when its pull request is removed from the merge queue.
    conditions:
      - queue-dequeue-reason != none
      - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: "Hey @{{author}}, your pull request has been dequeued due to the following reason: {{queue_dequeue_reason}}. Sorry about that, but you can requeue the PR by using `@mergifyio requeue` if you think this was a mistake."
queue_rules:
  - name: pre-commit Updates
    batch_size: 10
    allow_queue_branch_edit: true
    autoqueue: true
    queue_conditions:
      - files ~= .pre-commit-config.yaml
      - author = renovate[bot]
  - name: Dockerfile Updates
    batch_size: 5
    allow_queue_branch_edit: true
    autoqueue: true
    queue_conditions:
      - files ~= Dockerfile$
      - author = renovate[bot]
    merge_conditions:
      - check-success = Test Image / API Test
  - name: Github Actions Updates
    batch_size: 10
    allow_queue_branch_edit: true
    autoqueue: true
    queue_conditions:
      - files ~= ^.github/workflows
      - author = renovate[bot]
  - name: Python Dependency Updates
    allow_queue_branch_edit: true
    autoqueue: true
    queue_conditions:
      - files ~= ^(uv.lock|pyproject.toml)$
      - author = renovate[bot]
      - check-success = Check Dependency Compatibility
    merge_conditions:
      - check-success = Test Image / API Test
  - name: Docker Compose Updates
    batch_size: 10
    allow_queue_branch_edit: true
    autoqueue: true
    queue_conditions:
      - files ~= ^(docker-compose-dev.yaml|docker-compose.yaml)$
      - author = renovate[bot]
  - name: AUR Updates
    allow_queue_branch_edit: true
    autoqueue: true
    queue_conditions:
      - author = renovate[bot]
      - files ~= PKGBUILD$
      - deployment-success = pre-commit
    merge_conditions:
      - deployment-success = AUR
merge_protections_settings:
  post_comment: true
scopes:
  source:
    files:
      CI:
        include:
          - .github/workflows/*
      AUR:
        include:
          - "**/PKGBUILD"
      pre-commit:
        include:
          - .pre-commit-config.yaml
