name: Generate Resume
on: [push]
jobs:
    build_typst:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Set up Git repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Setup Typst
              uses: typst-community/setup-typst@13c527d2e8ac7863a24510c4043ad28fd47a5606 # v4.1.0
              with:
                cache-dependency-path: requirements.typ
            - name: Generate
              run: typst compile resume.typ docs/resume.pdf
            - name: Commit and Push new file
              uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
              with:
                commit_message: Update Docs
            - name: Create Release
              uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2
              with:
                files: docs/**
                generate_release_notes: true
                make_latest: true
                tag_name: ${{ github.run_number }}
