name: Generate Resume
on: [push]
jobs:
    build_typst:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v4.2.2
            - name: Set up Cache
              uses: actions/cache@v4.2.0
              with:
                  path: ~/.cache
                  key: ${{ runner.os }}-typst-${{ hashFiles('**/README.md') }}
                  restore-keys: ${{ runner.os }}-typst-
            - name: Setup Typst
              uses: typst-community/setup-typst@v3.1.0
              with:
                cache-dependency-path: requirements.typ
            - run: typst compile resume.typ resume.pdf
            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                files: resume.pdf
                generate_release_notes: true
                make_latest: true
                tag_name: ${{ github.sha }}
            - name: Commit and Push new file
              run: |
                  git config user.name MH0386          
                  git config user.email mohamed.hisham.abdelzaher@gmail.com         
                  git add resume.pdf        
                  git commit -m "Update Resume" 
                  git pull          
                  git push
              continue-on-error: true
      