name: Build LaTeX document
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v4.1.1
            - name: Set up Cache
              uses: actions/cache@v4.0.1
              with:
                  path: ~/.texlive
                  key: ${{ runner.os }}-texlive-${{ hashFiles('**/README.md') }}
                  restore-keys: ${{ runner.os }}-texlive-
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                  root_file: resume.tex
            - name: Upload PDF file
              uses: actions/upload-artifact@v4.3.1
              with:
                  name: PDF
                  path: resume.pdf
            - name: Commit and Push new file
              run: |
                  git config user.name MH0386          
                  git config user.email mohamed.hisham.abdelzaher@gmail.com         
                  git add .         
                  git commit -m "add PDF file" 
                  git pull          
                  git push
              continue-on-error: true
            - name: Delete Unwanted Files
              run: |
                  rm resume.aux resume.fdb_latexmk resume.fls resume.log resume.out
                  git config user.name MH0386          
                  git config user.email mohamed.hisham.abdelzaher@gmail.com         
                  git add .         
                  git commit -m "Delete Unwanted Files"       
                  git pull    
                  git push
