name: Build LaTeX document
on:
  push:
    branches:
      - main
env:
    ARTIFACT: PDF.zip
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume.pdf

      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.ARTIFACT }} -d dir
