name: LateX to PDF
on:
  push:
    branches: 
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Python3
        run: python3 
      - name: Install pdflatex
        run: pip install pdflatex
      - name: Script to generate PDF
        run: |
          from pdflatex import PDFLaTeX
          pdfl = PDFLaTeX.from_texfile("resume.tex")
          pdf, log, completed_process = pdfl.create_pdf(keep_pdf_file=True, keep_log_file=True)
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: resume.pdf
          path: resume.pdf
