name: LaTeX document CD
on:
  push:
    branches: 
      - main
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Build and release LaTeX document
        uses: TemplatesHub/gh-action-latex-build-and-release@v2
        with:
          tex-entry-point: 'resume'
          pdf-name: 'resume'
