name: LateX to PDF
on:
  push:
    branches: 
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Build LaTeX Document
        run: sudo apt-get install texlive texinfo texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra -y && pdflatex resume.tex
