name: LateX to PDF

on:
  push:
    branches: 
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: LaTeX-to-PDF github action
        uses: forkbabu/AutoEdit@v2.0
    
