name: Python application
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions:
    contents: read
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4.7.1
              with:
                  python-version: '3.10'
            - name: Install dependencies
              run: |
                curl -fsSL https://miktex.org/download/key | sudo tee /usr/share/keyrings/miktex-keyring.asc > /dev/null
                echo "deb [signed-by=/usr/share/keyrings/miktex-keyring.asc] https://miktex.org/download/ubuntu jammy universe" | sudo tee /etc/apt/sources.list.d/miktex.list
                sudo apt-get update
                sudo apt-get install miktex
                sudo miktexsetup --shared=yes finish
                initexmf --set-config-value [MPM]AutoInstall=1
                python -m pip install --upgrade pip
                pip install pdflatex
            - name: Run Python Script
              run: python convert.py
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3.1.3
              with:
                name: tmp
                path: tmp.zip
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: tmp
                path: .
            - name: Unzip artifact
              uses: montudor/action-zip@v1
              with:
                args: unzip -qq tmp.zip -d dir
